version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: db-postgres-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weyzer
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres
  mongo:
    image: mongo:latest
    container_name: db-mongo-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database_name
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
